---
# tasks file for roles/01-download-latest-artifact
- name: Get the response from Artifactory API regarding latest artifact
  uri:
    url: "http://192.168.56.88:8081/artifactory/api/storage/libs-snapshot-local/com/wipro/ConferenceRoomCapstoneB35/0.0.1-SNAPSHOT/?lastModified"
    url_username: admin
    url_password: Feb@2021
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
  register: data

- name: Save the JSON data to a Variable as a Fact
  set_fact:
    latestArtifactResponseAPI: "{{ data.content | from_json }}"

- name: Print the saved json response
  debug:
    var: latestArtifactResponseAPI

- name: Extract URI link from JSON file(uri response)regarding artifact details
  set_fact:
    artifactDetailsLink: "{{ latestArtifactResponseAPI | json_query(jmesquery) }}"
  vars:
    jmesquery: 'uri'  

- name: Display Artifact details link
  debug:
    var: artifactDetailsLink

- name: Get the artifact details regarding latest artifact from previously acquired link
  uri:
    url: "{{ artifactDetailsLink }}"
    url_username: admin
    url_password: Feb@2021
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
  register: details

- name: Save the JSON data related to artifact details into a Variable as a Fact
  set_fact:
    artifactDetails: "{{ details.content | from_json }}"

- name: Exhibit the details pertaining to the latest artifact
  debug:
    var: artifactDetails

- name: Extract URI link (location) of latest artifact from artifact details gathered in previous task
  set_fact:
    downloadUrl: "{{ artifactDetails | json_query(jmesquery) }}"
  vars:
    jmesquery: 'downloadUri'
    
- name: Debug the URI value
  debug: msg=" Newest Artifact Link => {{ downloadUrl }} ."

- name: Download the latest artifact uploaded into artifactory repository
  get_url:
    url: "{{ downloadUrl }}"
    dest: "{{ base_dir }}/{{ project_name }}/{{ sub_dir }}/ConferenceRoomCapstoneB35.war"
    url_username: admin
    url_password: Feb@2021
